version: 2
updates:
  # Composer dependencies
  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 5

  # npm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
      - 'devDependencies'
    open-pull-requests-limit: 5
