version: 2
updates:
  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 5

  - package-ecosystem: 'bun'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
      - 'devDependencies'
    open-pull-requests-limit: 5
